// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmcjuerftuicdosnubxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtY2p1ZXJmdHVpY2Rvc251Ynh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMzEyMDcsImV4cCI6MjA2NzcwNzIwN30.Im3f2oM_xwjrnAg6K_xof95C5YPsAZ8Kb1w5mwUNoXk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});